run:
  timeout: 5m
  skip-files:
    - \.pb\.go$
  go: '1.18'

issues:
  new: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - govet
    - ineffassign
    - misspell
    - typecheck
    - unconvert
    - whitespace
  disable:
    - deadcode
    - errcheck
    - goprintffuncname
    - gosimple
    - nilerr
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - unparam
    - unused
    - varcheck

linters-settings:
  gci:
    local-prefixes: github.com/Potterli20/trojan-go-fork
  goimports:
    local-prefixes: github.com/Potterli20/trojan-go-fork
