name: docker-release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
    tags: # let the GitHub CI with new tag release trigger this docker build GitHub CI
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
    
jobs:
  build:
    if: github.repository == 'Potterli20/trojan-go-fork'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUBUSERNAME }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "ref=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "ref=${GITHUB_SHA}" >> $GITHUB_ENV
          fi
          echo "docker_platforms=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386" >> $GITHUB_ENV
          echo "docker_image=${{ secrets.DOCKERUSERNAME }}/trojan-go-fork" >> $GITHUB_ENV
          echo "github_image=ghcr.io/${{ secrets.GITHUB_USERNAME }}/trojan-go-fork" >> $GITHUB_ENV

      - name: Build and push docker image
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag "${{ steps.prepare.outputs.docker_image }}:${GITHUB_REF#refs/tags/}" \
            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
            --tag "${{ steps.prepare.outputs.github_image }}:${GITHUB_REF#refs/tags/}" \
            --tag "${{ steps.prepare.outputs.github_image }}:latest" \
            --build-arg REF=${{ steps.prepare.outputs.ref }} \
            --file Dockerfile .
          else
            docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag "${{ steps.prepare.outputs.docker_image }}:snapshot" \
            --tag "${{ steps.prepare.outputs.github_image }}:snapshot" \
            --build-arg REF=${{ steps.prepare.outputs.ref }} \
            --file Dockerfile .
          fi

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Test docker image from Docker Hub
        run: |
          docker run --rm --entrypoint /usr/local/bin/trojan-go-fork ${{ secrets.DOCKERUSERNAME }}/trojan-go-fork -version

      - name: Test docker image from GitHub Packages
        run: |
          docker run --rm --entrypoint /usr/local/bin/trojan-go-fork ghcr.io/${{ secrets.GITHUB_USERNAME }}/trojan-go-fork -version
