name: Linter

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - ".github/workflows/linter.yml"
      - ".github/linters/.golangci.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - "**/*.go"
      - ".github/workflows/linter.yml"
      - ".github/linters/.golangci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.18.1

      - name: Checkout codebase
        uses: actions/checkout@main

      - name: golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: latest
          args: --config=.github/linters/.golangci.yml
          only-new-issues: true
